### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Estrella1024** [UoA-eResearch/leapmotion_gestures#9] opened 2020-10-18 01:21 UTC
Hello, I ran predict.py, and the output is always bad frame. The comment says that because the frame cannot be recorded, an exception is reported, but why can’t the frame be recorded? Can you help me?

**Comment by neon-ninja** [comment] 2020-10-19 03:05
Duplicate of #8

**Closed as completed by neon-ninja** 2020-10-19 03:05 UTC
Labels: question
